# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Xinhui Iris Lu
locale: en_US
email: xl2832@nyu.edu
description: >- # this means to ignore newlines until "baseurl:"
  Homepage for Xinhui(Iris)Lu
baseurl: "irislu.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  irislu6
avatar:  "/image/profile_1.jpeg"
search: true

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dirt" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins: jekyll-include-cache
layout: single


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      comments: true
      share: false
      related: true
      show_date: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "my_sidebar"



author:
  name: "Xinhui (Iris) Lu"
  avatar: "/image/profile_1.jpeg"
  bio: "MS in Management Inforamtion Systems, NYU" # Note: Markdown is allowed
  location: "New York, NY"
  github: irislu6
  linkedin: xinhuiirislu/
  email: xl2832@nyu.edu

# Collections
collections:
  Work_Experience:
    output: false
    permalink: /:collection/:path/
  Work_Experience2:
    output: false
    permalink: /:collection/:path/
  publications:
    output: false
    permalink: /:collection/:path/
  Internships:
    output: true
    permalink: /:collection/:path/
  Projects:
    output: true
    permalink: /:collection/:path/


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: false
      comments: false
  # _publications
  - scope:
      path: ""
      type: Internships
    values:
      layout: single
      author_profile: true
      share: false
      comments: false
  # _portfolio
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      share: false
      comment: false
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: single
      author_profile: true
      share: false
      comment: false
  # _Projects
  - scope:
      path: ""
      type: Projects
    values:
      layout: single
      author_profile: true
      share: false
      comment: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/New_York # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/irislu6"

    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/xinhuiirislu/"


    
      




# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
